server:
  port: 7777
  
spring:
  application:
    name: spring-cloud-study-zuul
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
zuul:
#需要忽略的头部信息，不在传播到其他服务
    sensitive-headers: Access-Control-Allow-Origin
    ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
    routes:
     apis1:
      path: /api1/**
      #serviceId: spring-cloud-study-demo
      serviceId: SPRING-CLOUD-STUDY-DEMO
     apis2:
      path: /api2/**
      url: http://127.0.0.1:9999/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #设置API网关中路由转发请求的HystrixCommand执行超时时间
ribbon:
  connectTimeout: 3000 #设置路由转发请求的时候，创建请求连接的超时时间
  readTimeout: 60000  #用来设置路由转发请求的超时时间