server:
  port: 8888
spring:
  application:
    name: EUREKA-CENTER
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/